### PR TITLE
Module 2 add bgp route summarization policies

### PR DESCRIPTION
**Pull request by miwamoto0203**
from maiwamot@cisco.com

### CODE REVIEW

**Review by juchowan — APPROVED** [review]

**Review by andbyrne — APPROVED** [review]
LGTM

**Comment by andbyrne** [comment]
Pending approval of schema change and updates to apply this policy under external EPG subnets.

**Comment by miwamoto0203** [comment]
as same as https://wwwin-github.cisco.com/netascode/nac-aci/pull/379,  we withdraw this at the moment. check the usage and will submit with items uses this policy if necessary.

**Comment by devegupt** [comment]
Created PR to attach the BGP Route Summarization Policy under Tenant -> L3Out -> External EPG -> Subnet .  https://github.com/netascode/terraform-aci-nac-aci/pull/120

**Pull request merged**
