### PR TITLE
Add descriptions to terraform-aci-aaep (#56)

### PR DESCRIPTION
**Pull request by therealdoug**
Resolves issue #56 to allow descriptions to be added to AAEP profiles

### CODE REVIEW

**Review by danischm — COMMENTED** [review]
Thanks for the PR! In order to update the documentation (readme), we need to run the pre-commit hooks after updating the code. If you need help setting this up let me know.

**Comment by therealdoug** [comment]
Sorry for the commit storm, was working through the pre-check setup. I'm new to it, but I think i was able to fumble my way through getting it set up using a combo of https://developer.cisco.com/docs/nexus-as-code/#!validations and just working through errors. 

I do believe this will pass the pre-commit checks now.  Thanks for your patience!

**Comment by danischm** [comment]
Looks like there is one more cosmetic update required: https://github.com/netascode/terraform-aci-nac-aci/actions/runs/8495474791/job/23276004674?pr=70

**Comment by therealdoug** [comment]
The version of terraform-docs I was using apparently had different output; using 0.16.0 appears to have resolved the cosmetic issue.  Again, thanks for the patience.

**Review by danischm — APPROVED** [review]

**Review by danischm — APPROVED** [review]

**Comment by danischm** [comment]
Thx for your contribution!

**Pull request merged**
