### PR TITLE
Module 8 fix l3out

### PR DESCRIPTION
**Pull request by dtatsumi-c**

### CODE REVIEW

**Review by andbyrne — CHANGES_REQUESTED** [review]
Can you please also add the same fix for the export route map?

**Comment by yoshaseg-451861** [comment]
@andbyrne 

> Can you please also add the same fix for the export route map?

Do you mean outbound_route_map?
Since outbound_route_map is a mandatory setting, we are only targeting inbound_route_map.
Should we fix the outbound_route_map as well?

**Comment by yoshaseg-451861** [comment]
> > @andbyrne
> > > Can you please also add the same fix for the export route map?
> > 
> > 
> > Do you mean outbound_route_map? Since outbound_route_map is a mandatory setting, we are only targeting inbound_route_map. Should we fix the outbound_route_map as well?
> 
> Both are optional in the module's variables.tf file. Please apply the same fix to both.

@andbyrne 

Understood, We will apply the fix to outbound as well.

**Comment by yoshaseg-451861** [comment]
@andbyrne 

The fix has also been applied to outbound. Please review the changes.

**Pull request merged**
